---
- hosts: all
  roles:
    - tersmitten.locales
    - basic
    - jnv.unattended-upgrades
    - nickjj.fail2ban
  vars:
    unattended_automatic_reboot_time: 05:00
    unattended_automatic_reboot: true
    unattended_origins_patterns:
      - 'origin=Debian,codename=${distro_codename},label=Debian-Security' # security updates
      - 'o=Debian,codename=${distro_codename},label=Debian' # updates including non-security updates
      #- 'o=Debian,codename=${distro_codename},a=proposed-updates'

- hosts: infra
  tasks:
  - name: "Create NFS directory structure"
    file:
      path: /shared/rhome/
      state: directory
      recurse: yes
  roles:
    - geerlingguy.nfs
  vars:
    nfs_exports: [ "/shared/rhome *(rw,sync,no_root_squash)"]

- hosts: all
  tasks:
  - name: "Create NFS directory structure"
    file:
      path: /nfs/rhome
      state: directory
      recurse: yes
  roles:
    - openmicroscopy.nfs-mount
  vars:
    nfs_share_mounts:
    - path: /nfs/rhome
      location: "192.168.2.11:/shared/rhome"